=== amantiwari8861/javaV1/javasrc-master/xml/src/main/java/xml/people.dtd
<!ELEMENT people (person)*>
<!ELEMENT person (name, email, country)>

<!ELEMENT name (#PCDATA)>
<!ATTLIST email type CDATA #IMPLIED>
<!ELEMENT email (#PCDATA)>
<!ELEMENT country (#PCDATA)>

=== amantiwari8861/javaV1/javasrc-master/xml/src/main/java/xml/people-xsl.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="people.xsl"?>
<!DOCTYPE people SYSTEM "people.dtd">

<people>
<person>
	<name>Ian Darwin</name>
	<email>http://www.darwinsys.com/</email>
	<country>Canada</country>
</person>
<person>
	<name>Another Darwin</name>
	<email type="intranet">ad</email>
	<country>Canada</country>
</person>
</people>

=== amantiwari8861/javaV1/javasrc-master/xml/src/main/java/xml/people-dtd.xml
<?xml version="1.0"?>
<!DOCTYPE people SYSTEM "people.dtd">
<people>
<person>
	<name>Ian Darwin</name>
	<email>http://www.darwinsys.com/</email>
	<country>Canada</country>
</person>
<person>
	<name>Another Darwin</name>
	<email type="intranet">afd@node1</email>
	<country>Canada</country>
</person>
</people>
