=== amantiwari8861/javaV1/javasrc-master/xml/src/main/java/xml/people.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2006 sp2 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="urn:darwinsys:people"
	xmlns:tns="urn:darwinsys:people" 
	elementFormDefault="qualified">

	<xs:element name="country">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Canada"/>
				<xs:enumeration value="USA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="email">
		<xs:complexType mixed="true">
			<xs:attribute name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="intranet"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string">
	</xs:element>
	<xs:element name="people">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:person" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="person">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:name"/>
				<xs:element ref="tns:email"/>
				<xs:element ref="tns:country"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== amantiwari8861/javaV1/javasrc-master/xml/src/main/java/xml/people-schema.xml
<?xml version="1.0"?>
<people xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="urn:darwinsys:people" 
	xsi:schemaLocation="urn:darwinsys:people ./people.xsd" >
	<person>
		<name>Ian Darwin</name>
		<email>http://www.darwinsys.com/</email>
		<country>Canada</country>
	</person>
	<person>
		<name>Another Darwin</name>
		<email type="intranet">afd@node1</email>
		<country>Canada</country>
	</person>
</people>
